return {
  {
    "mrjones2014/legendary.nvim",
    keys = {
      { "<C-S-p>", "<cmd>Legendary<cr>", desc = "Legendary" },
      { "<leader>hc", "<cmd>Legendary<cr>", desc = "Command Palette" },
    },
    opts = {
      which_key = { auto_register = true },
    },
  },
  {
    "folke/which-key.nvim",
    cond = function()
      return require("config").keymenu.which_key
    end,
    dependencies = {
      "mrjones2014/legendary.nvim",
    },
    event = "VeryLazy",
    opts = {
      preset = "modern",
      plugins = { spelling = true },
      replace = {
        key = {
          { "<Space>", "SPC" },
          { "<leader>", "SPC" },
        },
      },
      triggers = {
        { "<auto>", mode = "nixsotc" },
      },
      win = {
        border = "single",
        padding = { 1, 1 },
      },
      layout = {
        height = { min = 4, max = 25 },
        width = { min = 20, max = 50 },
        spacing = 3,
        align = "left",
      },
      spec = {
        mode = { "n", "v" },
        { "<leader>w", "<cmd>update!<CR>", desc = "Save" },
        { "<leader>q", group = "Quit/Session" },
        { "<leader>qq", function() require("utils").quit() end, desc = "Quit" },
        { "<leader>qt", "<cmd>tabclose<cr>", desc = "Close Tab" },
        { "<leader>a", group = "AI" },
        { "<leader>b", group = "Buffer" },
        { "<leader>d", group = "Debug" },
        { "<leader>D", group = "Database" },
        { "<leader>f", group = "File" },
        { "<leader>ft", function() require("utils").open_term("yazi") end, desc = "Terminal File Manager" },
        { "<leader>h", group = "Help" },
        { "<leader>j", group = "Jump" },
        { "<leader>g", group = "Git" },
        { "<leader>gh", group = "Hunk" },
        { "<leader>gt", group = "Toggle" },
        { "<leader>gw", group = "Work Tree" },
        { "<leader>n", group = "Notes" },
        { "<leader>p", group = "Project" },
        { "<leader>r", group = "Refactor" },
        { "<leader>t", group = "Test" },
        { "<leader>tN", group = "Neotest" },
        { "<leader>to", desc = "Overseer" },
        { "<leader>v", group = "View" },
        { "<leader>z", group = "System" },
        { "<leader>s", group = "Search" },
        { "<leader>sc", function() require("utils.coding").cht() end, desc = "Cheatsheets" },
        { "<leader>so", function() require("utils.coding").stack_overflow() end, desc = "Stack Overflow" },
        { "<leader>l", group = "Language" },
        { "<leader>lg", group = "Annotation" },
        { "<leader>lx", group = "Swap Next" },
        { "<leader>lxf", desc = "Function" },
        { "<leader>lxp", desc = "Parameter" },
        { "<leader>lxc", desc = "Class" },
        { "<leader>lX", group = "Swap Previous" },
        { "<leader>lXf", desc = "Function" },
        { "<leader>lXp", desc = "Parameter" },
        { "<leader>lXc", desc = "Class" },
        { "<leader>c", group = "ChatGPT" },
        { "<leader>cc", "<cmd>ChatGPT<CR>", desc = "ChatGPT" },
        { "<leader>ce", "<cmd>ChatGPTEditWithInstruction<CR>", desc = "Edit with instruction", mode = { "n", "v" } },
        { "<leader>cg", "<cmd>ChatGPTRun grammar_correction<CR>", desc = "Grammar Correction", mode = { "n", "v" } },
        { "<leader>ct", "<cmd>ChatGPTRun translate<CR>", desc = "Translate", mode = { "n", "v" } },
        { "<leader>ck", "<cmd>ChatGPTRun keywords<CR>", desc = "Keywords", mode = { "n", "v" } },
        { "<leader>cd", "<cmd>ChatGPTRun docstring<CR>", desc = "Docstring", mode = { "n", "v" } },
        { "<leader>ca", "<cmd>ChatGPTRun add_tests<CR>", desc = "Add Tests", mode = { "n", "v" } },
        { "<leader>co", "<cmd>ChatGPTRun optimize_code<CR>", desc = "Optimize Code", mode = { "n", "v" } },
        { "<leader>cs", "<cmd>ChatGPTRun summarize<CR>", desc = "Summarize", mode = { "n", "v" } },
        { "<leader>cf", "<cmd>ChatGPTRun fix_bugs<CR>", desc = "Fix Bugs", mode = { "n", "v" } },
        { "<leader>cx", "<cmd>ChatGPTRun explain_code<CR>", desc = "Explain Code", mode = { "n", "v" } },
        { "<leader>cr", "<cmd>ChatGPTRun roxygen_edit<CR>", desc = "Roxygen Edit", mode = { "n", "v" } },
        { "<leader>cl", "<cmd>ChatGPTRun code_readability_analysis<CR>", desc = "Code Readability Analysis", mode = { "n", "v" } },
      },
    },
    config = function(_, opts)
      local wk = require "which-key"
      wk.setup(opts)
    end,
  },
}
